spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/test;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true